name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - master  # Ruleaza doar pe push in branch-ul 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: axiomatic-skill-458008-j5                                                     #ID-ul proiectului GCP
      REGION: europe-west2                                                                      #Regiunea unde se face deploy
      SERVICE_NAME: fastapi-app                                                                 #Numele serviciului Cloud Run
      IMAGE: europe-west2-docker.pkg.dev/axiomatic-skill-458008-j5/fastapi-app/fastapi-app

    steps:
        # 1.Clonare cod din repo
      - name: Checkout code
        uses: actions/checkout@v3

        # 2. Autentificare folosind key-ul JSON din secrets
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.FST_SA_KEY }}
      
        # 3. Instalare CLI gcloud
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

        # 4. Autentificare Docker pentru Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

        # 5. Build imagine Docker local
      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE }} .

        # 6. Push imagine in Artifact Registry
      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{ env.IMAGE }}

        # 7. Deploy pe Cloud Run, cu injectare secret
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --max-instances=3 \
            --service-account=github-workflow-deployer@${{ env.PROJECT_ID }}.iam.gserviceaccount.com \
            --set-secrets=SERVICE_ACCOUNT_KEY_JSON=SERVICE_ACCOUNT_KEY_JSON:latest