name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - master  # folosești master, nu main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: axiomatic-skill-458008-j5
      REGION: europe-west2
      SERVICE_NAME: fastapi-app
      IMAGE: europe-west2-docker.pkg.dev/axiomatic-skill-458008-j5/fastapi-app/fastapi-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.FST_SA_KEY }}
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE }} .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --max-instances=3 \
            --service-account=github-workflow-deployer@${{ env.PROJECT_ID }}.iam.gserviceaccount.com \
            --set-secrets=SERVICE_ACCOUNT_KEY_JSON=SERVICE_ACCOUNT_KEY_JSON:latest